language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: "RZoE05KgJFx/IDEoRfOCuJW+ns6dkPnFqt3wT5lSTyTW8dTGhMjC8yuaTjk04Fl/CaFOGxI5Mj6hHq45SZGiTWSeahJFwGciVdSOSyuPaJPmZfzM5PMU1aKQDH89Ulm8uSqnipEL/aZOqpKIFFEs6fz14cqneC+rQr6eK6m+Em+YxYH2ZRy9JzU8ds6lOp/A08D3rUH3kcSDIsQ68qOzrEatINYs+xDLcbedJSsrw7FEk1xGFCqNjHYS4CP9Tsq7I63oryn6RS0DhhUM/K59kPqPplohRCAIZwStkbflG14fjt2SFlcnK3anSIHUxiydXmSFaHA/9trsRq5nr9NNJGC2v1xqw+OUoi1biryOpNfKdj0HYxIIcXhq1TDMCqZVjiJ0hnFLwUqZziQnpKfML74s/GOmMzEaLwrFlD9NPsHBLbcZKlZZINyUJbmRPDBjeDnbAlRgHfbggfq2TxZjVVa+XsbrtIGT8w93gVcmFkCQVZciPqApLAU8VV5Dnuu4ztABhH57W72pN9odthfsUqv7kvSG+s+OY1Lm98iX7XeHJkqABjnXCKkkfL0YLLup+QON5PeFvzAPBIFVxv8PDgF5N5KTdQKEUHDZ1HMcZRuonEykiTDDyURLqKcX8b6lu1VCfAim1aI64d5wgFcx+NyNTUj3TDhBILddeZanJnc="
  app: abcontrol-spring-boot-microser